###
// GET ALL ORDERS WITH STATUS IN PROGRESS (userType: all)
GET http://localhost:28852/orderIncomplete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjJAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6OCwiZXhwIjoxNjk2NjgwNTM1fQ.j2QYSy1FjMaN_wJIBQRXgl4JIK2Su4KrvjXKbdlBQJo

###
// MARK ORDER AS READY (userType: staff)
POST http://localhost:28852/order/3/markReady
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjJAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6OCwiZXhwIjoxNjk2NjgwNTM1fQ.j2QYSy1FjMaN_wJIBQRXgl4JIK2Su4KrvjXKbdlBQJo

###
// GET ALL ORDERS (userType: all)
GET http://localhost:28852/orderHistory
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjJAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6OCwiZXhwIjoxNjk2NjgwNTM1fQ.j2QYSy1FjMaN_wJIBQRXgl4JIK2Su4KrvjXKbdlBQJo

###
// GET ORDER BY ID (userType: all)
GET http://localhost:28852/order/4
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjJAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6OCwiZXhwIjoxNjk2NjgwNTM1fQ.j2QYSy1FjMaN_wJIBQRXgl4JIK2Su4KrvjXKbdlBQJo

###
// CREATE NEW ORDER (userType: all)
POST http://localhost:28852/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZkBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InN0YWZmIiwidXNlcklkIjoxLCJleHAiOjE2OTY5NDAyMDR9.kzZbPTVPJkT44SJUn6WzMnxo32Jw5jR26m8KCPYIta0

{
  "mealIds": [3, 4]
}

###
// GET ALL CATEGORIES (userType: all)
GET http://localhost:28852/categories
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjJAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6OCwiZXhwIjoxNjk2OTM5MjE4fQ.UrVdzZMXakrc0B7fXQdf6dFWf6TUhzhJxM9BqcUOux0

// GET CATEGORY BY ID (userType: all)
GET http://localhost:28852/categories/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjJAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6OCwiZXhwIjoxNjk2NjgwNTM1fQ.j2QYSy1FjMaN_wJIBQRXgl4JIK2Su4KrvjXKbdlBQJo

###
// ADD NEW CATEGORY (userType: staff)
POST http://localhost:28852/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZkBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InN0YWZmIiwidXNlcklkIjoxLCJleHAiOjE2OTY5NDAyMDR9.kzZbPTVPJkT44SJUn6WzMnxo32Jw5jR26m8KCPYIta0

{"title": "Category2",
"description": "Test Category 2"}

###
// GET ALL MEALS (userType: all)
GET http://localhost:28852/meals
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZkBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InN0YWZmIiwidXNlcklkIjoxLCJleHAiOjE2OTY5NDAyMDR9.kzZbPTVPJkT44SJUn6WzMnxo32Jw5jR26m8KCPYIta0

###
// GET MEAL BY ID (userType: all)
GET http://localhost:28852/meals/3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjJAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6OCwiZXhwIjoxNjk2OTM5MjE4fQ.UrVdzZMXakrc0B7fXQdf6dFWf6TUhzhJxM9BqcUOux0

###
// ADD A MEAL (userType: staff)
POST http://localhost:28852/meals
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZkBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InN0YWZmIiwidXNlcklkIjoxLCJleHAiOjE2OTY5NDAyMDR9.kzZbPTVPJkT44SJUn6WzMnxo32Jw5jR26m8KCPYIta0

{
  "title": "Test Meal2",
  "price": 11.5,
  "imageUrl": "https://www.google.com",
  "categoryIds": [2]
}

###
// DELETE USER FROM JWT TOKEN (userType: all)
DELETE http://localhost:28852/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjNAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6MTAsImV4cCI6MTY5NjY3OTYzMn0.w2TiAuK9Zd9KIfpy_S0Tcya5IU--xnsBwidlos7TsYA

###
// UPDATE USER FROM JWT TOKEN (userType: all)
PUT http://localhost:28852/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjNAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6MTAsImV4cCI6MTY5NjY3OTYzMn0.w2TiAuK9Zd9KIfpy_S0Tcya5IU--xnsBwidlos7TsYA

{"email": "staff3@email.com",
  "userType": "staff",
  "password": "password123",
  "name": "test",
  "phone": "+79999999999",
  "address": "address"}

###

###
// GET USER INFO FROM JWT TOKEN (userType: all)
GET http://localhost:28852/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjNAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6MTAsImV4cCI6MTY5NjY3OTYzMn0.w2TiAuK9Zd9KIfpy_S0Tcya5IU--xnsBwidlos7TsYA

###
// DELETE USER (userType: staff)
DELETE http://localhost:28852/user/9 (userType: all)
Accept: application/json

###
// UPDATE USER (userType: staff)
PUT http://localhost:28852/user/9
Content-Type: application/json

{"email": "staff3@email.com",
  "userType": "staff",
  "password": "password123",
  "name": "name",
  "phone": "+79999999999",
  "address": "address"
}

###
// GET USER BY ID (userType: staff)
GET http://localhost:28852/user/8
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjJAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6OCwiZXhwIjoxNjk2NzgwMjI5fQ.BjmNbi7sxl-vO5OWGsA7t1xRubQs-3SpLPZq6bAiNls

###
// GET ALL USERS (userType: staff)
GET http://localhost:28852/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjJAZW1haWwuY29tIiwidXNlclR5cGUiOiJTVEFGRiIsInVzZXJJZCI6MiwiZXhwIjoxNjk2OTUwNDQ1fQ.DJFnMb5DR7Yz9xO28TpFd0ZX-5LX_t8AybEjoVhSH2E

###
// VALIDATE JWT TOKEN (userType: all)
GET http://localhost:28852/validate
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZkBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6IlNUQUZGIiwidXNlcklkIjoxLCJleHAiOjE2OTY5NTA0NDV9.P5y4SBPLF_USxhFEt6M9QYFtgDkw_J9LNbh_PWfkDyc

###
// AUTHENTICATE USER (no auth)
POST http://localhost:28852/signin
Content-Type: application/json

{"email": "staff2@email.com",
  "password": "password123"}

###
// REGISTER USER (no auth)
POST http://localhost:28852/signup
Content-Type: application/json

{
  "email": "staff2@email.com",
  "userType": "STAFF",
  "password": "password123"
}

###
